os: linux
dist: bionic
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_bdba505e7122_key -iv $encrypted_bdba505e7122_iv
  -in oci_data.tar.enc -out $TRAVIS_BUILD_DIR/oci_data.tar -d
- tar -xvf $TRAVIS_BUILD_DIR/oci_data.tar -C $TRAVIS_BUILD_DIR/
- rm -rf ~/.ansible
install:
- pip install -r tests/requirements.txt
- pip install -r requirements-dev.txt
- pip install -r requirements.txt
stages:
- prepare
- config_tests
- cluster_tests
- instance_orchestration_tests
- instance_configurer_tests
- vcn_tests
if: commit_message =~ ^.*\[ci\].*$ OR tag IS present
jobs:
  include:
  - stage: prepare
    python: '3.6'
    script: &1
    - python setup.py check -rms
    - flake8
  - stage: prepare
    python: '3.7'
    script: *1
  - stage: prepare
    python: '3.8'
    script: *1
  - stage: config_tests
    python: '3.6'
    script: &2
    - travis_wait pytest -s -v tests/test_config.py
  - stage: config_tests
    python: '3.7'
    script: *2
  - stage: config_tests
    python: '3.8'
    script: *2
  - stage: cli_tests
    python: '3.6'
    script: &3
    - travis_wait pytest -s -v tests/test_cli.py
  - stage: cli_tests
    python: '3.7'
    script: *3
  - stage: cli_tests
    python: '3.8'
    script: *3
  - stage: cluster_tests
    python: '3.6'
    script:
    - travis_wait pytest -s -v tests/test_cluster_stack.py
    - travis_wait pytest -s -v tests/test_cluster_orchestrator.py
  - stage: instance_orchestration_tests
    python: '3.6'
    script: travis_wait pytest -s -v tests/test_instance_orchestrator.py
  - stage: instance_orchestration_tests
    python: '3.7'
    script: travis_wait pytest -s -v tests/test_instance_orchestrator.py
  - stage: instance_orchestration_tests
    python: '3.8'
    script: travis_wait pytest -s -v tests/test_instance_orchestrator.py
  - stage: instance_configurer_tests
    python: '3.6'
    before_script: &4
    - mkdir $TRAVIS_BUILD_DIR/.ssh/
    - ssh-keygen -t rsa -b 4096 -N "" -f $TRAVIS_BUILD_DIR/.ssh/oci_id_rsa
    env:
    - OCI_INSTANCE_SSH_KEY=$TRAVIS_BUILD_DIR/.ssh/oci_id_rsa
    - ANSIBLE_HOST_KEY_CHECKING=False
    script: travis_wait pytest -s -v tests/test_instance_configurer.py
  - stage: instance_configurer_tests
    python: '3.7'
    before_script: *4
    env:
    - OCI_INSTANCE_SSH_KEY=$TRAVIS_BUILD_DIR/.ssh/oci_id_rsa
    - ANSIBLE_HOST_KEY_CHECKING=False
    script: travis_wait pytest -s -v tests/test_instance_configurer.py
  - stage: instance_configurer_tests
    python: '3.8'
    before_script: *4
    env:
    - OCI_INSTANCE_SSH_KEY=$TRAVIS_BUILD_DIR/.ssh/oci_id_rsa
    - ANSIBLE_HOST_KEY_CHECKING=False
    script: travis_wait pytest -s -v tests/test_instance_configurer.py
  - stage: vcn_tests
    python: '3.6'
    script: travis_wait pytest -s -v tests/test_vcn_*.py
  - stage: vcn_tests
    python: '3.7'
    script: travis_wait pytest -s -v tests/test_vcn_*.py
  - stage: vcn_tests
    python: '3.8'
    script: travis_wait pytest -s -v tests/test_vcn_*.py
  - stage: deploy
    python: '3.6'
    script: &5
    - python setup.py sdist bdist_wheel
    deploy: &6
      skip_cleanup: true
      skip_existing: true
      distributions: sdist bdist_wheel
      provider: pypi
      user: __token__
      password:
        secure: R4WWdmEXt5RIKKblang9srOKh8ZT17dxOddoJeKhlvDi0mhxlCAZaw50zA8RcuSWI1iLgmqP3piVw6YwQmbewCGuQh4NiTjTBLh3Dm398nazbDCOBdCCtI46PJC6Ng54UntuDLgyLVjwmvEM0UK8tnrYpUH9YE+KHsoaQnE3lYHez2kmXVt1uuBnXJurOuVo03vFfixjNL+obFZ3IBJe9E/h9GBIg13qTRt6nU3xSDbw4FgUKMoXfLYZnu2/Kb/SCcENlVFx2BLxUtCyTmGpmLf4h7mbhaZlvgf8P46HM5iU9hvbiFlQ5UojJQmJdlzK2XP+2+4bLMHGyn/mhmA9R7IUVmxpo0SKO3ZZk0D68j5fiipL0DdqLMaSGvB+JEiIB5F+K3HjTcZ6r+iKjM6icXA9WZ2SDXybMxz3ad95KJn0A+sS+s/Z4vho5vWAWDpO9TYNIJxcZDfdKbX/wkDkiVGJhoJPVAhSAP/Cr0dYnbKtyGT5Re6YYbztfkuHVX7/pH1O67zmzGc6dUcCkJX0PjHmOp5GrVJDM21MGLjP0G1XgzQxy9qQxucBtNfMQB4AMDbHbTBflzVa8T7cFWRt8iruQlPtzwHqGqF3sgSlsZ5tyjOB5oIO2dC9e2bzYe94rBVZi8TU9k6mMwaMUmWk/AOvWDs8VLlYaRPjFhqYgWo=
      on:
        tags: true
        branch: master
  - stage: deploy
    python: '3.7'
    script: *5
    deploy: *6
  - stage: deploy
    python: '3.8'
    script: *5
    deploy: *6
env:
  global:
  - OCI_CONFIG_DIR="$TRAVIS_BUILD_DIR/.oci"
  - OCI_CONFIG_PATH="$OCI_CONFIG_DIR/config"
  - OCI_KEY_FILE="$OCI_CONFIG_DIR/test_api_info"
  - CORC_PROVIDERS_OCI_TEST_ID="$TRAVIS_JOB_ID-$TRAVIS_JOB_NUMBER"
  - CORC_PROVIDERS_OCI_PROFILE_NAME="DEFAULT"
  - secure: cTxYL2PDcAQeHRMJOP8zj5ytTqCurAEg5c6bB03zZ7nRA2PfOCDOohzzfBpmD2ztROg2HcRmM3JSr0mIyJMKHrn6kFq6tcotVpfFVyC/bfOrHmkl3ttnun3GdswBnOrjUrPnHJ5CjTciuWTPexa35rKsU4veATfXNSws1bpQNcl48PZYrhIqd5ekpmtaxzH1ONyelP4zkLNFNeoobTS7NF9FsKBas1HELGGqHoia550fx6xh26wPPD90dFw8vbLLT0iq3giYpaltXlxIK7EJnmbYXZ51s5iMCuDBhQLUcFEB8b4phJPADROvZSjXXd45b3xFWWc29RoHqEajSE+RdyzdqDd0eucFdFMd91IX3gHCJb1OqV2NAclBbGayy6V0KZmKHD4cT74A5CN5en0HvUh7K6HUuwDMEXUJL8xSv+UMbaOOvZBkM9qgcTtVNjOR6y5OQtmBYQ79p5gTFbM5QP64ggcoaffJQssepC/g6sp129jlS46+o+vo62Mv8FvCd6RsWBDVZ8nQZhWy6VLmQTEpidEx0XhCUGZuV4OGIP7lSToKZjU8YtIkDTafzabUSPBlC0IqFSY+Q3jqXdlCTa2VFN8s/bYhOWnM7Zt/xjYjiBCjNOJQJnF0q6LKkgorjktq2SvXjalfrDOTJd4WGiChrfGnrpR7hwlj/O4UBqw=
  - secure: ABPG9/BEWz1z26olQ8TfGx6dqfHEAYTzMvL09qKkj02x+BTL6/XQgjpD5Xo6gOgmoZqge1w1bQtVZHBPCbzay4HIS4AGeWOeEyEC0TTaxtFwfsy7jzou5eggYEfmqusqNk3H5qKu3oW6v6SY/0dl3gnWKWWxekzKljl2AM/klh4k/a5jbwFAQ/JhTyaf60wLPzXa53qyIoBNOg9TE7oK5xDa/RcQTPGJ37VLU8q4TsbynkJTg1awpCtGiLmORTe40AP9N2BmBdo/inIvFAjm/TlSoyGl00ljE+kSeujiv6kctUM1vkLUGwMQcqqmbsutNIVzxUHDiMP9fqpBpN7kC3oNRy5HjV+EEvKdHxR4wvlRsNQaJxS5qePP3Fl274vPV7+qQiNwomGbEn3ApWrfHjJG9wmSNy9EOiFSEY4OrWsRcWrAHtbMm/AEX1TQWwhy9IJy9WFqCDQPpnNyBCVp992clMYLvbVizst3hBVKtFh2tC0WZpneM0QnqwY9Zxiz0ZvIaA01rE10H1zOyqpmraaCa01rdeOYFi552bH4ErD/x25ykLfDRZdCX8rJ9LB77zFcP5Voy+azvWorCFrvnO8O+3fsYkFqs39pzKlOBADlW3aDocOi8ZKc9CewDFzlOTuN8fxcQf71FJuRUId5fvd5zKrVznaOFB5y6jBNLPc=
  - secure: WZNveCPbqqvH5tYoTRrWq6UmERnyv3ahC+BvVS9R9kKygS9twL9K2bSFVXvVLfIL5H2IGSEdVvG1NAI+cr2yV3ZKtlBswgDL0BwzKcybXJflQA53Ig0U0E3dtX8m1kJhNuxkIK5DxZ07zHlM95/aO8VEJwEoA0yePxNLxTW8qjVLxEzT/6zQBy56oBg4F9CY1nCyqSXMox4OI1enduRVJJaPl9UKH156mBZ3ig3g2YFFcUfAA4nYMTEqd6ijUbKvz5zYP5RIOL59kkszoA/nd4Sf1LId+PLKNQx0dWIWPOVKOIWRo2i/jXwmV2ZlXlwKMEv01oMW4qdSo851OSp4SzB4Um1Sw0y+DEQqYm6q/8ZAs6UfzkEFcGzQrtT1qK4dPBFrahytfc/EgkUYPl4ZkZg3SfzfWoY87Wno+lGRpahTR9CIBExY0ZZAI+LRX2MhmglpNyv9289tsi2IYG1RuOrXsCcXVDUanOzUG2xTZPh+fQgqMRpyfzigleJFpA7L83lkBKTBp3k0e6VSCYlVTScZ7UUuiAKacu1rCgFsNc7GkkKOBzq99l2/ov+Do8/3p3mkDg9oTdbblLpEMzxSL+jj1z6rKIq6XTgTz2pyszvgl7jVh/9zTOYOtOa3XoIImipog5xbEwPfmhqoZ8S4SBP91FRe0THeMukTzzzfQNc=
