os: linux
dist: bionic
language: python
python:
- '3.6'
- '3.7'
- '3.8'
before_install:
- mkdir $TRAVIS_BUILD_DIR/.oci
- openssl aes-256-cbc -K $encrypted_bdba505e7122_key -iv $encrypted_bdba505e7122_iv
  -in oci_data.tar.enc -out $TRAVIS_BUILD_DIR/oci_data.tar -d
- tar -xvf $TRAVIS_BUILD_DIR/oci_data.tar -C $TRAVIS_BUILD_DIR/
install:
- pip install -r tests/requirements.txt
- pip install -r requirements-dev.txt
- pip install -r requirements.txt
script:
- python setup.py check -rms
- flake8
- travis_wait pytest -s -v tests/
deploy:
  skip_cleanup: true
  distributions: sdist bdist_wheel
  provider: pypi
  user: rasmunk
  on:
    tags: true
    branch: master
    python: '3.7'
env:
  global:
  - secure: Pck6ytGvxHS/UZK7oXw9kPDoouH8MB5uy5QoB0bb3BWGeUiLsWyMPqpVbkib0ZCduXVHzgbuHaWwiUnY8plf7yZ+KSJzD57Xp4oMrfSOyqCvhQUY2U+hMu8jAupcxlSgCS7EbPF5vsuyUWWyIHvCwAtoRzHc1RBek4GsIn+esbicUkftnyyDNIW48FrG+PoyDDNOHnWXMr9Sa031MZljQIoLbsuoyifNoURiKi3Hx6pymwwdRvVVGiCXzUNctnLJDpIhdImu44vdjKppAbib1cqhMyBX/JFpzpS8qPN7DpmjfmuNzuqKtOdk7Fp6oNNu7Q76299Bq0/7MwF1yNwcdU4VctYeQPKKVTF7NgkE4yKHBhS1TmblbSZ/eImDQ1qaEQk2ll/iZKblIoUwTaZbuVgVlR2EaIexdiYTwO/JveLq126KlgvJRyoLPIgADTCsO5X9fb5Cib5SEXyg3APVtqvR0CdsCgLvLQSmocNxI0c3GsxxLmUmjfrRQsbAUJd4jVisqsIOiPbifB1IbfZLW1muWpYR1QF/MAis7Ak3aHSZw8gHiQ4ycBFjyTtn02z4D3YQ43SNdDEm4UKU35/DATjw+QgDPUeSsXne6xaM6TR8ZWmrJIq34md0e+YYtkkD/1qEl0nzkl9eV/swRQF5BZr5gkfiqs3px/VzaEbFsTo=
  - secure: VwtxZc3BUCk8tkJnutBFvjlvoiw8I6qbkW6kIVM6g7P9L7HRRrvl+drfvNlrbxZx03NT9MK6L5BUaj/aD/WMbzgTN+7CiEtQ7r6stSqHCypCyWLedwWwLM1QDNj0kiG38cZGgxszIsG9JOx/YEkjRv/gCuRkKc/3tmtLAnwRaINpiOD4pz+ohiadKOGmD9jpjPTgGmzfMMlpHOEIPqh+I3QKqrrN9RkZ2tdZjZgIe43giovWFpU+aIohJWXRuVIy2auaPwqmY0DRqrki0MfkQsDrVowQRyIUBfLqwcGTmutSsS7r+xPWZmDjNztKYXoIfsWRl6MSPl5nkUH+Y7U+7+fBaUB3kfSAO5o37gltcpkiZolRiJ0bJaszZ2y1qsIrcvyTwNWlg6mz/067Li2JNopQiOzSvUDpigLJ3tjijVM4nPkquFXV3G+tKCIK7GOqxoKqOouGz2o1eY/yz7aYJjtLCWKjKyECx46w/tt8nWDDWb25mFEmmuCVngfEtYV+cNRasBJ7ca8pRy/dgEMQBRxZ4lKmnkmrAyoKrkWYFouPlNdIoUWYlmrfXsoJc/BIQ2nhUl+T28YKoGzTjYnnD+saoQA0NA/Qausp0guvN6N9Lfsk62ArLTRA+mYMhy0SKAlsghNEHLo3YrD2zjpcUXW5AJKBZKp1/kG/oFw1qt4=
  - secure: E3EJe/ea7zYt3X4sS+gqj8YiZkm3OIaeDUDwFfARiXRwDEoeovjrlacgkEZPGD3gdV05bpx6i6+ylg6ACx6KcwKBAsQbuGxrLW37WWSOvkeNfcGKH3a07wDbQd80Rj+tkqzjRqiE0exA/0lPQNPMs/xHIYynAKIn6+FEdJu/7yKWNjTdh0240mpwkzw91g7UYKjIw6py3HtEP5E45jvauhwIQFfjhY/k3Hcw3wNGh/+niUjT+8bYuGWAI/ISHFHxsubBT9Ey3kYu1A7tHTDDkL7jkj69tqaTvKY8ynH8NDm/x9TGQZfFAh6hYv15nEzSuYMijIwOe32IWTzMv7GpzsvtUJQWwRyCZPlt/fDDbgwIueleCm2ZRHyKSZz7UddPuMdFY9yfsauIGLl4OEi5zEsrc7RPUskXC7QjAq2EIQ31JaaGJdoCyf92t/TsMquiopaZYq7UQwYhOEN+CA9nVqxjFj8bgEZZoAw4sQbtcYk1o2TWOhLsQdTjbqLLVC8NfOOKNIrBG1rn0Gwd4E9y+1jeABar5wlZtTTQ9CcA+6ys5gaWObSrYtFF4kEfzPBPc1zx4H9lJnedic7OmlKHevQ+ar/XjDNDHbEQJ8+lyhWhPiCjjaU+qIg4XWIiYXhvpQfPBnCTJA3w4ABaTTcqvTKthrEGL11EDGxsBFgmhwI=
