os: linux
dist: bionic
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_bdba505e7122_key -iv $encrypted_bdba505e7122_iv
  -in oci_data.tar.enc -out $TRAVIS_BUILD_DIR/oci_data.tar -d
- tar -xvf $TRAVIS_BUILD_DIR/oci_data.tar -C $TRAVIS_BUILD_DIR/
- rm -rf ~/.ansible
install:
- pip install -r tests/requirements.txt
- pip install -r requirements-dev.txt
- pip install -r requirements.txt
stages:
- prepare
- config_tests
- cluster_tests
- instance_orchestration_tests
- instance_configurer_tests
- vcn_tests
if: commit_message =~ ^.*\[ci\].*$ OR tag IS present
jobs:
  include:
  - stage: prepare
    python: '3.6'
    script: &1
    - python setup.py check -rms
    - flake8
  - stage: prepare
    python: '3.7'
    script: *1
  - stage: prepare
    python: '3.8'
    script: *1
  - stage: config_tests
    python: '3.6'
    script: &2
    - travis_wait pytest -s -v tests/test_config.py
  - stage: config_tests
    python: '3.7'
    script: *2
  - stage: config_tests
    python: '3.8'
    script: *2
  - stage: cluster_tests
    python: '3.6'
    script:
    - travis_wait pytest -s -v tests/test_cluster_stack.py
    - travis_wait pytest -s -v tests/test_cluster_orchestrator.py
  - stage: instance_orchestration_tests
    python: '3.6'
    script: travis_wait pytest -s -v tests/test_instance_orchestrator.py
  - stage: instance_orchestration_tests
    python: '3.7'
    script: travis_wait pytest -s -v tests/test_instance_orchestrator.py
  - stage: instance_orchestration_tests
    python: '3.8'
    script: travis_wait pytest -s -v tests/test_instance_orchestrator.py
  - stage: instance_configurer_tests
    python: '3.6'
    before_script: &3
    - mkdir $TRAVIS_BUILD_DIR/.ssh/
    - ssh-keygen -t rsa -b 4096 -N "" -f $TRAVIS_BUILD_DIR/.ssh/oci_id_rsa
    env:
    - OCI_INSTANCE_SSH_KEY=$TRAVIS_BUILD_DIR/.ssh/oci_id_rsa
    - ANSIBLE_HOST_KEY_CHECKING=False
    script: travis_wait pytest -s -v tests/test_instance_configurer.py
  - stage: instance_configurer_tests
    python: '3.7'
    before_script: *3
    env:
    - OCI_INSTANCE_SSH_KEY=$TRAVIS_BUILD_DIR/.ssh/oci_id_rsa
    - ANSIBLE_HOST_KEY_CHECKING=False
    script: travis_wait pytest -s -v tests/test_instance_configurer.py
  - stage: instance_configurer_tests
    python: '3.8'
    before_script: *3
    env:
    - OCI_INSTANCE_SSH_KEY=$TRAVIS_BUILD_DIR/.ssh/oci_id_rsa
    - ANSIBLE_HOST_KEY_CHECKING=False
    script: travis_wait pytest -s -v tests/test_instance_configurer.py
  - stage: vcn_tests
    python: '3.6'
    script: travis_wait pytest -s -v tests/test_vcn_*.py
  - stage: vcn_tests
    python: '3.7'
    script: travis_wait pytest -s -v tests/test_vcn_*.py
  - stage: vcn_tests
    python: '3.8'
    script: travis_wait pytest -s -v tests/test_vcn_*.py
  - stage: deploy
    python: '3.6'
    script: &4
    - python setup.py sdist bdist_wheel
    deploy: &5
      skip_cleanup: true
      skip_existing: true
      distributions: sdist bdist_wheel
      provider: pypi
      user: __token__
      password:
        secure: R4WWdmEXt5RIKKblang9srOKh8ZT17dxOddoJeKhlvDi0mhxlCAZaw50zA8RcuSWI1iLgmqP3piVw6YwQmbewCGuQh4NiTjTBLh3Dm398nazbDCOBdCCtI46PJC6Ng54UntuDLgyLVjwmvEM0UK8tnrYpUH9YE+KHsoaQnE3lYHez2kmXVt1uuBnXJurOuVo03vFfixjNL+obFZ3IBJe9E/h9GBIg13qTRt6nU3xSDbw4FgUKMoXfLYZnu2/Kb/SCcENlVFx2BLxUtCyTmGpmLf4h7mbhaZlvgf8P46HM5iU9hvbiFlQ5UojJQmJdlzK2XP+2+4bLMHGyn/mhmA9R7IUVmxpo0SKO3ZZk0D68j5fiipL0DdqLMaSGvB+JEiIB5F+K3HjTcZ6r+iKjM6icXA9WZ2SDXybMxz3ad95KJn0A+sS+s/Z4vho5vWAWDpO9TYNIJxcZDfdKbX/wkDkiVGJhoJPVAhSAP/Cr0dYnbKtyGT5Re6YYbztfkuHVX7/pH1O67zmzGc6dUcCkJX0PjHmOp5GrVJDM21MGLjP0G1XgzQxy9qQxucBtNfMQB4AMDbHbTBflzVa8T7cFWRt8iruQlPtzwHqGqF3sgSlsZ5tyjOB5oIO2dC9e2bzYe94rBVZi8TU9k6mMwaMUmWk/AOvWDs8VLlYaRPjFhqYgWo=
      on:
        tags: true
        branch: master
  - stage: deploy
    python: '3.7'
    script: *4
    deploy: *5
  - stage: deploy
    python: '3.8'
    script: *4
    deploy: *5
env:
  global:
  - OCI_TEST_ID="$TRAVIS_JOB_ID-$TRAVIS_JOB_NUMBER"
  - OCI_CONFIG_DIR="$TRAVIS_BUILD_DIR/.oci"
  - OCI_CONFIG_PATH="$OCI_CONFIG_DIR/config"
  - OCI_KEY_FILE="$OCI_CONFIG_DIR/test_api_info"
  - secure: p5Yjduuxz8eIGQXYzMHQB2ftU5YsbGrhJat37mt6XwfplNnKTyQlRmTkban98gASqhIMDDvPr65KKsUwzjUdRAmZE9zHY1pu/5EUENzWPK/d2TlQTsSuNYIDnGN/Fx/BkBI0/3ec8f9jkjwaW+FvewavWkB1yQrdvreYAS/gEaC6soD8U1Y3TCxxsmgNpehL7fJh9NR2xeSEDeFDasJiDdkso5Von2oZDwFvJDzKnyUN/dmtpn+sQNj7ebkBU6FAa5HPGacWFtM3U/d1ncDCiVfHOHBlSmDlPYhWtDLQ8+ciuX+0D7RnH5n8efQc6Aivk4dCR4yaDTBnBI2DiBOeyDIhx+42pF19kWqyLjdqBiEOG/trwg01pNYF3A+P1eGtVrxLLQffraqjygFaZhfYOkbGSciuvnBqVs+uiLPJ563jJO3TAfIeWWl5cVnqJ8fMGARvohqMykXwSFQznQb44iL//yUbdlAhkhAEnjT/M16WmbbP9EUkVnDLMPUGJ1DIgPS843lRGABRFkWPxOVyMbLXbGn+TNuiRr2+duNJLkTg7hB3sokmUdCtCGk/8koIFKVbylmfyHrZOJOf10sxyK8dVkJ3TL1QoJr41wYUVKiFWLLgOmttTPSpqK8YUglkGDbKyoC4ALmmbeak9N2PqYoZF7lWtV5BG89tmGLpEYA=
