os: linux
dist: bionic
language: python
python:
- '3.6'
- '3.7'
- '3.8'
before_install:
- mkdir $TRAVIS_BUILD_DIR/.oci
- openssl aes-256-cbc -K $encrypted_bdba505e7122_key -iv $encrypted_bdba505e7122_iv
  -in oci_data.tar.enc -out $TRAVIS_BUILD_DIR/oci_data.tar -d
- tar -xvf $TRAVIS_BUILD_DIR/oci_data.tar -C $TRAVIS_BUILD_DIR/
install:
- pip install -r tests/requirements.txt
- pip install -r requirements-dev.txt
- pip install -r requirements.txt
script:
- python setup.py check -rms
- flake8
- travis_wait pytest -s -v tests/
deploy:
  skip_cleanup: true
  distributions: sdist bdist_wheel
  provider: pypi
  user: rasmunk
  on:
    tags: true
    branch: master
    python: '3.7'
env:
  global:
  - secure: Pck6ytGvxHS/UZK7oXw9kPDoouH8MB5uy5QoB0bb3BWGeUiLsWyMPqpVbkib0ZCduXVHzgbuHaWwiUnY8plf7yZ+KSJzD57Xp4oMrfSOyqCvhQUY2U+hMu8jAupcxlSgCS7EbPF5vsuyUWWyIHvCwAtoRzHc1RBek4GsIn+esbicUkftnyyDNIW48FrG+PoyDDNOHnWXMr9Sa031MZljQIoLbsuoyifNoURiKi3Hx6pymwwdRvVVGiCXzUNctnLJDpIhdImu44vdjKppAbib1cqhMyBX/JFpzpS8qPN7DpmjfmuNzuqKtOdk7Fp6oNNu7Q76299Bq0/7MwF1yNwcdU4VctYeQPKKVTF7NgkE4yKHBhS1TmblbSZ/eImDQ1qaEQk2ll/iZKblIoUwTaZbuVgVlR2EaIexdiYTwO/JveLq126KlgvJRyoLPIgADTCsO5X9fb5Cib5SEXyg3APVtqvR0CdsCgLvLQSmocNxI0c3GsxxLmUmjfrRQsbAUJd4jVisqsIOiPbifB1IbfZLW1muWpYR1QF/MAis7Ak3aHSZw8gHiQ4ycBFjyTtn02z4D3YQ43SNdDEm4UKU35/DATjw+QgDPUeSsXne6xaM6TR8ZWmrJIq34md0e+YYtkkD/1qEl0nzkl9eV/swRQF5BZr5gkfiqs3px/VzaEbFsTo=
  - secure: Ptxp+Sn6VawfZ/jVa0fPh9/Szyze8l780+mslNahwNQnq8veOtoB3X68B2KjfpiQQ92aBINWWDGSdKLiflGM87gGDJuIJ1SjqNaeZGdsZnZtcJGgXjX5jnG65SZHH4m8MiILbMssCHirH9xyeONthrc91rIscEidNkMWyQ44IKaFmDZRFbCpY3Xf36HhDKj8yUT0fTHcXwmqS6IQ77U7Q529lJ5XzY3CQP9px2KQ6CWdMgAmlcRQomqSCELm/vWzJbuV2VrsJt/p8NpJnNilwpDx2NLRXOPwnR9UlkZSA+5vw1HmfI+U7EFq0fJPEJRburJomJEiEzwKN4IsvX0IKkQWI37OExaAGnZ4aBv/KOYNnBBjy+lQjmRwWZ3MpoQHXhAmsIJhLYrNWelb9qb4ITfYI7l7hQhq0W+vyXF8XXqJTu1d9ismE9JiChPkaONaQ0e1jDsR0nP6TsVDcUCid4qImfeBCngfe/zOU9DlLgmIthTMtdGM/d/TCLqwimm6GT+FmCb2aRHsh4v51hqaxjJKC6zAlAPr6abjXV7QsH0pFRdRoMpMiLosNB3oMQqepkzrnPpiMvvmZvRh6tVwWALsRKzG4MawmtK9ZlmxaI9oNBtGgKP7H89nyEX6xpd6dYRE65gb9KdGvmSNzW6EJI2r5RjWqhNbILAPfi4EmTA=
  - secure: fDkxgvbjydSRa+PnG/VQGnn6fqMV36Owy7s6qRNDI5SyWqxNJ/9gPxzqsaRzIHaExQWhCkiFGcR/01hR7pO+lx+MGN/Ge6acdIilPvi00pHXPTTYyOKOLo+0R2D2G74Y0qKaV0deut+DMBVDz57islAfDglfIfLAmDKPyIRO44xvtCtCzptpcTwLpG3E2VrDBpuBlMoRGlG9uQA30LMyLI4Oig4rAnj7FhfNjDWu+fFsW2Ve6b/cgvHhOw+EPNqpnqejpN1jA5cotc0o2rdmfaYeA9RSUYW6mqGxLSZSB6Dbhmi6QQmN87uTOuKfro+G8XbxB7FHmXEnmxy4GuGXnyudbpml42O/RDm2jKRpr+u6Dea5Vv+bWH56XD3BzhxTXFRr5nhxuh9IGPS6UqnB1t7H5cbtRCr1P3nszeE8GUrYZ2/tNjvjt2t2E9ncyNeJ3QHl/3Bt5fFxFI/wNdRIb+LMjR0hFYislFovo8NUDlprHqrUSyH2cZ1Au3NEvvjw0+HwerpR9P4v3D+xEaFfK7Zo5iIVCXOcKm9RgXAiFnIPL4fwlLF+OftBLFyOQIl/tklGETWxfu1LbwrhiKwjM2ALk+I1xGWHZ4zt3E/J01jIJ6XEyrlsBuVECvxbejPQKKr4HaxxqLLTMNhkvJOejZUcHkcom1LNRxDchsNAwUQ=
