language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r tests/requirements.txt
- pip install -r requirements.txt
script:
- python setup.py check -rms
- flake8
- travis_wait pytest -s -v tests/
deploy:
  skip_cleanup: true
  distributions: sdist bdist_wheel
  provider: pypi
  user: rasmunk
  on:
    tags: true
    branch: master
    python: '3.7'