environments:
  pypi_package:
    environment_variables:
      TWINE_USERNAME: "{{SECRET:[pypi][corc][username]}}"
      TWINE_PASSWORD: "{{SECRET:[pypi][corc][password]}}"
    pipelines:
      - corc
pipelines:
  corc:
    group: pypi_package
    locking: off
    materials:
      corc_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/rasmunk/corc.git
        branch: master
        destination: corc
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: corc
      TEST_DIRECTORY: corc
      PUSH_DIRECTORY: publish-python-scripts
    template: pypi_package