environments:
  corc:
    environment_variables:
      GIT_USER: "{{SECRET:[github][username]}}"
      PYPI_USERNAME: "{{SECRET:[corc][username]}}"
      PYPI_PASSWORD: "{{SECRET:[corc][password]}}"
    pipelines:
      - corc
format_version: 10
pipelines:
  corc:
    display_order: -1
    group: bare_metal_pypi_package
    label_template: ${COUNT}
    lock_behaviour: none
    timer:
      # Run on the 1st at 00:00 of every month
      spec: "0 0 0 1 * ? *"
      only_on_changes: no
    materials:
      corc_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/rasmunk/corc.git
        branch: master
        destination: corc
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: corc
      TEST_DIRECTORY: corc
      PUSH_DIRECTORY: publish-python-scripts
    template: bare_metal_pypi_package
